upload:
    path: ''
    methods: ['POST']
    controller: d_media.media_controller::upload

update:
    path: /{id<\d+>}
    methods: ['PUT']
    controller: d_media.media_controller::update

delete:
    path: /{id<\d+>}
    methods: ['DELETE']
    controller: d_media.media_controller::delete

find:
    path: /{id<\d+>}
    methods: [ 'GET', 'HEAD' ]
    controller: d_media.media_controller::find

getList:
    path: ''
    methods: ['GET', 'HEAD']
    controller: d_media.media_controller::getList
