services:
    Djvue\DMediaBundle\:
        resource: '../../'
        autowire: true
        autoconfigure: true
        public: true
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../DTO/'
            - '../../Security/'
            - '../../DMediaBundle.php'

    Djvue\DMediaBundle\Security\:
        resource: '../../Security'
        autowire: true
        public: true

    d_media.media_service:
        class: Djvue\DMedia\Service\MediaService

    d_media.media_entity_service:
        class: Djvue\DMedia\Service\MediaEntityService

    d_media.media_controller:
        class: Djvue\DMedia\Controller\MediaController
